blank_issues_enabled: false
contact_links:
  - name: "Report a Bug / Feature Request"
    url: https://codeberg.org
    about: "Please open all issues and feature requests on our canonical Codeberg repository."
  - name: "Discussions & Community"
    url: https://codeberg.org
    about: "Join the ProFed community on Codeberg."
